# The Docker image that will be used to build your app
image: busybox
pages:
  stage: deploy
  script:
    - mkdir /tmp/public
    - cp -R ./ /tmp/public
    - mv /tmp/public/ ./public
  artifacts:
    paths:
      - public
