# The Docker image that will be used to build your app
image: busybox
pages:
  stage: deploy
  script:
    - mkdir public
    - shopt -s extglob
    - cp -R !(public) public
  artifacts:
    paths:
      - public
